# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - xvfb-run julia -e 'Pkg.clone(pwd()); Pkg.build("Immerse"); Pkg.test("Immerse"; coverage=true)'
