# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: true
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - xvfb-run julia -e 'Pkg.clone(pwd()); Pkg.build("Immerse"); Pkg.test("Immerse"; coverage=true)'
